version: 2.1

commands:
  setup_sbt:
    description: "Set up SBT"
    parameters:
      version:
        type: string
        default: "1.3.3"
    steps:
      - run:
          name: Install SBT
          command: |
            curl -L -o sbt-<< parameters.version >>.deb https://dl.bintray.com/sbt/debian/sbt-<< parameters.version >>.deb
            sudo dpkg -i sbt-<< parameters.version >>.deb
            rm sbt-<< parameters.version >>.deb

  save_sbt_cache:
    description: "Save SBT cache"
    steps:
      - save_cache:
          key: sbt-cache-{{ sha256sum .circleci/config.yml }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "~/.coursier"

jobs:
  sbt_tests:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - setup_sbt
      - run:
          name: test sbt
          command: |
            date
            echo "Hello World"
      - save_sbt_cache
  sbt_tests2:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: PWD
          command: |
            pwd
            ls
            id
            df .
      - restore_cache:
          keys:
            - sbt-cache-{{ sha256sum .circleci/config.yml }}
      - run:
          name: PostRestoreCheck
          command: |
            pwd
            ls ~/.ivy2

workflows:
  version: 2
  one_and_two:
    jobs:
      parameters:
        sbt-cache-id:
          type: string
          value: "1.1.1"
      - sbt_tests
      - sbt_tests2:
          requires:
            - sbt_tests

